export const ContractKeys = {
    OPERATOR: "OPERATOR",
    USERS_MAPPING_PREFIX: "USERS",
    ORDERS_MAPPING_PREFIX: "ORDERS",
    PRODUCTS_MAPPING_PREFIX: "PRODUCTS",
    EMPLOYEES_MAPPING_PREFIX: "EMPLOYEES"
};